DROP TABLE CLIENTE_MEDICAMENTO CASCADE CONSTRAINTS PURGE;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS PURGE;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTE CASCADE CONSTRAINTS PURGE;

CREATE TABLE CLIENTE (
  ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY, 
  NOMBRE VARCHAR2(20 BYTE) NOT NULL, 
  APELLIDO VARCHAR2(20 BYTE) NOT NULL, 
  GENERO VARCHAR2(20 BYTE), 
  CORREO VARCHAR2(50 BYTE) NOT NULL, 
  DIRECCION VARCHAR2(100 BYTE), 
  TELEFONO NUMBER NOT NULL, 
  CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE MEDICAMENTO (
  ID_MEDICAMENTO NUMBER GENERATED ALWAYS AS IDENTITY, 
  NOMBRE VARCHAR2(20 BYTE) NOT NULL, 
  FARMACEUTICA VARCHAR2(20 BYTE), 
  FECHA_INGRESO DATE NOT NULL, 
  FECHA_VENCIMIENTO DATE NOT NULL, 
  CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (ID_MEDICAMENTO)
);

CREATE TABLE EMPLEADO (
  ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY, 
  NOMBRE VARCHAR2(20 BYTE) NOT NULL, 
  APELLIDO VARCHAR2(20 BYTE) NOT NULL, 
  CORREO VARCHAR2(50 BYTE) NOT NULL, 
  TELEFONO NUMBER NOT NULL, 
  FECHA_CONTRATACION DATE NOT NULL, 
  SALARIO NUMBER NOT NULL, 
  CONSTRAINT EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE CLIENTE_MEDICAMENTO (
  ID_CLIENTE_MEDICAMENTO NUMBER GENERATED ALWAYS AS IDENTITY, 
  ID_CLIENTE NUMBER NOT NULL, 
  ID_MEDICAMENTO NUMBER NOT NULL, 
  CONSTRAINT CLIENTE_MEDICAMENTO_PK PRIMARY KEY (ID_CLIENTE_MEDICAMENTO),
  CONSTRAINT CLIENTE_MEDICAMENTO_FK1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
  CONSTRAINT CLIENTE_MEDICAMENTO_FK2 FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO (ID_MEDICAMENTO)
);


CREATE TABLE ALMACEN
(
  ID_ESTANTE NUMBER NOT NULL,
  NOMBRE_ESTANTE VARCHAR2(30 BYTE) NOT NULL,
  CONSTRAINT ALMACEN_PK PRIMARY KEY (ID_ESTANTE)
);


CREATE TABLE ALMACEN_MEDICAMENTO
(
  ID_ALMACEN_MEDICAMENTO NUMBER NOT NULL,
  ID_ESTANTE NUMBER NOT NULL,
  ID_MEDICAMENTO NUMBER NOT NULL,
  CONSTRAINT ALMACEN_MEDICAMENTO_PK PRIMARY KEY (ID_ALMACEN_MEDICAMENTO)
);

CREATE TABLE FACTURA
(
  ID_FACTURA NUMBER NOT NULL,
  NOMBRE VARCHAR2(20 BYTE) NOT NULL,
  APELLIDO VARCHAR2(20 BYTE) NOT NULL,
  CORREO VARCHAR2(50 BYTE) NOT NULL,
  DIRECCION VARCHAR2(100 BYTE) NOT NULL
  TELEFONO NUMBER NOT NULL,
  PRODUCTOS VARCHAR2(20 BYTE) NOT NULL,
  TOTAL NUMBER NOT NULL,
  CONSTRAINT FACTURA_PK PRIMARY KEY (ID_FACTURA)
);

CREATE TABLE FACTURA_EMPLEADO
(
  ID_FACTURA_EMPLEADO NUMBER NOT NULL,
  ID_FACTURA NUMBER NOT NULL,
  ID_EMPLEADO NUMBER NOT NULL,
  CONSTRAINT FACTURA_EMPLEADO_PK PRIMARY KEY (ID_FACTURA_EMPLEADO)
);

CREATE TABLE MEDICAMENTO (
  ID_MEDICAMENTO NUMBER GENERATED ALWAYS AS IDENTITY, 
  NOMBRE VARCHAR2(20 BYTE) NOT NULL, 
  FARMACEUTICA VARCHAR2(20 BYTE), 
  FECHA_INGRESO DATE NOT NULL, 
  FECHA_VENCIMIENTO DATE NOT NULL, 
  CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (ID_MEDICAMENTO)
);



